# The name of the mod loader type to load
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[25.0,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/BogdanW3/Test/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
    # The modid of the mod
    modId="test"
    # The version number of the mod
    version="1.1.0"
     # A display name for the mod
    displayName="Test Mod 1.13.2"
    # The description text for the mod (multi line!)
    description=''' This is my mod, there may be others, but this one is test '''
    # A URL to query for updates
    updateJSONURL="https://raw.githubusercontent.com/BogdanW3/Test/master/promotions_slim.json"